[package]

name = "srg"
version = "0.0.1"
authors = ["thecoshman <thecoshman@gmail.com>"]

[dependencies.xlib]

git = "http://github.com/servo/rust-xlib.git"

[dependencies.glx]

# git = "https://github.com/servo/rust-glx.git"
git = "https://github.com/rpjohnst/rust-glx.git"
